config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  
  resources :events do
    resources :attendees_events, only: [:new, :create, :destroy]
    member do
      get 'attend'
      get 'unattend'
    end
  end

  resources :users, only: [:show]
    
  get '/users/edit/delete_user_image', to: 'users#delete_user_image'
  

  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendees_event.rb
class AttendeesEvent < ApplicationRecord
  validates_uniqueness_of :attendee_id, scope: :event_id
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where("date < ?", Date.today) } 
  scope :upcoming, -> { where("date >= ?", Date.today) }
  
  belongs_to :creator, class_name: 'User'
  has_many :attendees_events, dependent: :destroy
  has_many :attendees, through: :attendees_events, dependent: :destroy
  has_one_attached :image

  validates :title, :description, :date, :time, :location, :image, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy
  has_many :attendees_events, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendees_events, source: :event, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/attendees_events_controller.rb
class AttendeesEventsController < ApplicationController
  private

  def attendees_event_params
    params.require(:attendees_event).permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = Event.all
  end

  def show
  end

  def attend
    @event = Event.find(params[:id])

    attendees_events = AttendeesEvent.new(attendee_id: current_user.id, event_id: @event.id)
    if attendees_events.save
      redirect_to @event, notice: "You are now attending this event!"
    else
      redirect_to @event, alert: "You are already attending this event!"
    end
  end

  def unattend
    @event = Event.find(params[:id])
    attendees_events = AttendeesEvent.find_by(attendee_id: current_user.id, event_id: @event.id)
    attendees_events.destroy

    redirect_to @event, notice: "You are no longer attending this event!"
  end

  def new
    @event = current_user.created_events.build
  end

  def edit
  end

  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event created!" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end 
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event updated!" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end 
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: "Event deleted!" }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :time, :location, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  def delete_user_image
    @user_image = ActiveStorage::Attachment.find_by(id: current_user.image.id)
    @user_image.purge_later
    redirect_back(fallback_location: root_path)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_events_helper.rb
module AttendeesEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>

    <%= f.error_notification %>

    <div class="field">
        <div class="control">
            <%= f.input :title, wrapper: false, required:true, input_html: { class: "input" }, label_html: { class: "label" } %>
        </div>
    </div>
    <div class="field">
        <div class="control">
            <%= f.input :description, wrapper: false, required: true, input_html: { class: "textarea" }, label_html: { class: "label" } %>

        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :location, wrapper: false, required:true, input_html: { class: "input" }, label_html: { class: "label" } %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :date, wrapper: false, label_html: { class: "label" }, html5: true, required: true %> 
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.input :time, wrapper: false, label_html: { class: "label" }, html5: true, required: true%> 
        </div>
    </div>
    
    <div class="file">
        <div class="control">
            <%= f.label :image, class: "label m-0", required: true %> <br>
            <div class="file is-normal">
                <label class="file-label">
                    
                    <%= f.input_field :image, class: "file-input" %> 
                    <span class="file-cta">
                    <span class="file-label">
                        Upload a Picture
                    </span>
                    </span>
                </label>
            </div>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.button :submit, wrapper: false, class: "button is-danger mt-5" %>
        </div>
    </div>

<% end %>

app/views/events/_past.html.erb
<% @events.past.each do |event| %>

    <div class="column is-one-quarter-fullhd is-one-quarter-widescreen is-one-third-desktop is-half-tablet  is-half-mobile card-column">
        <div class="card remove-links-color">
            <%= link_to event do %>
                <div class="card-image">
                    <figure class="image is-16by9">
                        <% if event.image.attached? %>
                            <%= image_tag(event.image) %>
                        <% end %>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content">
                        <p class="has-text-weight-semibold is-size-6 event-title"> <%= event.title %> </p>
                        <p class="event-date has-text-danger has-text-weight-medium"> <%= event.date.strftime("%a, %b %d,") %> <%= event.time.strftime("%I:%M %p") %> </p>
                    <% end %>

                    <p class="has-text-grey"> <%= event.location %> </p>
                    <p class="has-text-weight-semibold mt-3 "> <%= event.creator.name %> </p>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/events/_upcoming.html.erb
<% events.upcoming.each do |event| %>

    <div class="column is-one-quarter-fullhd is-one-quarter-widescreen is-one-third-desktop is-half-tablet  is-half-mobile card-column ">
        <div class="card remove-links-color">
            <%= link_to event do %>
                <div class="card-image">
                    <figure class="image is-16by9">
                        <% if event.image.attached? %>
                            <%= image_tag(event.image) %>
                        <% end %>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content">
                        <p class="has-text-weight-semibold is-size-6 event-title"> <%= event.title %> </p>
                        <p class="event-date has-text-danger has-text-weight-medium"> <%= event.date.strftime("%a, %b %d,") %> <%= event.time.strftime("%I:%M %p") %> </p>
                    <% end %>

                    <p class="has-text-grey"> <%= event.location %> </p>
                    <p class="has-text-weight-semibold mt-3 "> <%= event.creator.name %> </p>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/events/edit.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-5">
                <h1 class="title"> Edit Event </h1>

                <div class="box">
                    <%= render 'form', event: @event %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/events/index.html.erb
<section id="main-hero" class="hero is-halfheight"> 
    <div class="container "> 
        <h2 id="main-hero-text" class="title is-size-1"> 
        Ready. <br> Set. <br> Plan. 
        </h2>
    
    </div>
</section>

<section id="events-container" class=section>
    <div class="container">
        <h2 class="title is-3">Upcoming Events</h2>
        <div class="columns is-multiline is-variable is-5 is-mobile">
            <%= render 'upcoming', events: @events %>
        </div>
    </div>

    <div class="container mt-5">
        <h2 class="title is-3">Past Events</h2>
        <div class="columns is-multiline is-variable is-5 is-mobile">
            <%= render 'past', events: @events %>
        </div>
    </div>
</section>

app/views/events/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-5">
                <h1 class="title"> Create an Event </h1>

                <div class="box">
                    <%= render 'form', event: @event %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/events/show.html.erb
<section class=" show-header section is-medium">

    <div class="container">
        <div class="columns">
            <div class="column is-8">
                <h1 class="title"> <%= @event.title %> </h1>
                <div class="media">
                    <figure class="media-left">
                        <p class="image is-64x64">
                            <% if @event.creator.image.attached? %>
                                <%= image_tag @event.creator.image, class:"is-rounded" %>
                            <% else %>
                                <img class="is-rounded" src="https://bulma.io/images/placeholders/64x64.png">
                            <% end %>

                            
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content remove-links-color">

                            <%= link_to user_path(@event.creator.id)  do %>
                                <p> Hosted by <br> <span class="has-text-weight-semibold"> <%= @event.creator.name %>  </span> </p>
                            <% end %>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
</section>

<section class="section show-main">
    <div class="container">
        <div class="columns is-centered reverse-columns ">

            <div class="column is-two-thirds">
                <div class="content event-description">
                    <h2 class="subtitle"> About this event </h2>
                    <p> <%= @event.description %> </p>
                </div>

                <div class="block attendees">
                    <h3 class="title"> Attendees (<%= @event.attendees.count %>) </h3>
                    <div class="columns is-multiline is-variable is-mobile">
                        <% @event.attendees.each do |attendee| %>
                            <div id="attendee-card" class="column is-one-quarter-fullhd is-one-quarter-widescreen is-one-third-desktop is-two-fifths-tablet is-half-mobile ">
                                <%= link_to user_path(attendee.id) do %>
                                    <div class="card ">
                                        <div class="card-image">
                                            <figure class="image is-64x64">
                                                <% if attendee.image.attached? %>
                                                    <%= image_tag attendee.image, class:"is-rounded" %>
                                                <% else %>
                                                    <img class="is-rounded" src="https://bulma.io/images/placeholders/64x64.png">
                                                <% end %>
                                            </figure>
                                        </div>
                                        <div class="card-content">
                                            <p class="has-text-weight-semibold has-text-centered"> <%= attendee.name %> </p>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %> 
                    </div>
                </div>
            </div>

            <div class="column">

                <% if @event.date.past? %>
                    <button class="button is-danger is-medium mb-4 attend-btn" disabled>
                        Event Has Passed!
                    </button>
                <% else %>
                    <% if  user_signed_in? && AttendeesEvent.exists?(attendee_id: current_user.id, event_id: @event.id) %>
                        <%= link_to 'Unattend', unattend_event_path(@event.id), 
                                                class: "attend-btn button is-danger is-light mb-4 is-medium" %>
                    <% else %>
                        <%= link_to 'Attend', attend_event_path(@event.id), 
                                            class: "attend-btn button is-danger mb-4 is-medium" %>
                    <% end %>
                <% end %>

                <div class="box">
                    <div class="media">
                        <div class="media-left">
                            <img src="https://img.icons8.com/material-outlined/50/000000/clock--v1.png"/>
                        </div>
                        <div class="media-content">
                            <p> <%=@event.date.strftime("%A, %B %d, %Y ")%> <br> <%= @event.time.strftime("%I:%M %p") %> </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if flash[:notice] %>
      <div class="notification is-primary ">
        <button class="delete"></button>
        <p class="notice"> <%= notice %> </p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger ">
        <p class="alert"> <%= alert %> </p>
      </div>
    <% end %>

      <% unless controller_name == 'registrations' && controller.action_name != 'edit' || controller_name == 'sessions' && controller.action_name != 'create' %>

        <nav class="navbar is-white">
          <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
              <h1 class="title is-4"> Eventlite </h1>
            <% end %>
          </div>

          <div class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <% if user_signed_in? %>
                    <%= link_to 'Create Event', new_event_path, class: "button is-danger control" %>
                   
                  <% else %>
                    <%= link_to "Sign In", new_user_session_path, class: "button is-white control" %>
                    <%= link_to "Sign Up", new_user_registration_path, class: "button is-danger is-light control" %>
                  <% end %>
                  
                </div>
              </div>

              <% if user_signed_in? %>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                      <% if current_user.image.attached? %>
                        <%= image_tag current_user.image, class: "navbar-profile-img" %>
                      <% else %>
                        <img class="is-rounded" src="https://img.icons8.com/ios-glyphs/60/000000/user--v1.png"/>
                      <% end %>
                    
                  </a>

                  <div class="navbar-dropdown is-right">
                    <%= link_to 'Profile', user_path(current_user.id), class:"navbar-item" %>

                    <%= link_to 'Settings', edit_user_registration_path, class:"navbar-item" %>
                    
                    <hr class="navbar-divider">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  </div>

                </div>
              <% end  %>
              
              
            </div>
          </div>
        </nav>
      <% end %>

    



    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<section class="section has-border-bottom">
    <div class="container" id="user-info">
        <div class="media">

            <figure class="media-left">
                <p class="image profile-image">
                    <% if @user.image.attached? %>
                        <%= image_tag @user.image, class: "is-rounded" %>
                    <% else %>
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    <% end %>
                </p>
            </figure>

            <div class="media-content">
                <h2 class="title mb-5"> <%= @user.name %> </h2>
                <h2 class="subtitle has-text-weight-semibold mb-2"> Member since <%= @user.created_at.strftime("%B %Y") %> </h2>

                <span class="icon-text mb-1">
                    <span class="icon">
                        <i class="las la-calendar "></i>
                    </span>
                    <span>  Hosted <%= pluralize(@user.created_events.count, 'event') %> </span>
                </span>

                <span class="icon-text">
                    <span class="icon">
                        <i class="las la-users"></i>
                    </span>
                    <span>  Attended <%= pluralize(@user.attended_events.count, 'event') %> </span>
                </span>

            </div>
        </div>
        <div class="level">
            <div class="level-left">
                
            </div>
            <div class="level-right">
                <% if @user == current_user %> 
                    <%= link_to 'Edit Profile', edit_user_registration_path, class:"button is-danger"  %>
                <% end %>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-vcentered jcc">
            <div class="column is-9">
                <h2 class="title">All Events</h2>

                <% @user.created_events.each do |event| %>
                
                    <div class="block has-border-top-bottom user-show-event p-2 remove-links-color">
                        <%= link_to event do %>
                            <div class="media">
                                <div class="media-left">
                                    <p class="image is-128x128">
                                        <% if event.image.attached? %>
                                            <%= image_tag event.image %>
                                        <% else %>
                                            <img src="https://bulma.io/images/placeholders/128x128.png">
                                        <% end %>
                                    </p>
                                </div>
                                <div class="media-content">
                                    <p class="has-text-weight-semibold is-size-6 event-title"> <%= event.title %> </p>
                                    <p class="event-date has-text-danger has-text-weight-medium"> <%= event.date.strftime("%a, %b %d,") %> <%= event.time.strftime("%I:%M %p") %> </p>
                                    <p> <%= event.location %> </p>
                                    <p class="has-text-grey"> <%= pluralize(event.attendees.count, 'Attendees') %> </p>

                                    <div class="level is-mobile">
                                        <div class="level-left"></div>
                                        <div class="level-right">
                                            <div class="level-item">
                                                <% if @user == current_user %>

                                                    <%= link_to edit_event_path(event), class: "mr-2" do %>
                                                        <span class="icon">
                                                            <i class="las la-edit is-size-5"></i>
                                                        </span>
                                                    <% end %>

                                                    <%= link_to event, method: :delete, data: { confirm: "Are you sure you want to delete this event?" } do %>
                                                        <span class="icon">
                                                            <i class="las la-trash-alt is-size-5"></i>
                                                        </span>
                                                    <% end %>
                                                    
                                                <% end %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</section>